"""
Pytest configuration and fixtures for fine-tuning tests.

Sets up the Python path to properly import backend modules.
Mocks modules that require Docker environment (database connections, etc.)

NOTE: Tests should be run inside Docker with:
    docker compose run --rm backend pytest tests/test_finetuning.py -v
    
Or with all dependencies installed locally.
"""

import sys
import os
from pathlib import Path
from types import ModuleType

import pytest

# Add the backend directory to the Python path
backend_dir = Path(__file__).parent.parent
sys.path.insert(0, str(backend_dir))

# Set environment variables for testing
os.environ.setdefault("REDIS_URL", "redis://localhost:6379/0")
os.environ.setdefault("STORAGE_DIR", "/tmp/test_storage")
os.environ.setdefault("DATA_DIR", "/tmp/test_data")


def check_dependencies():
    """Check if required dependencies are available."""
    missing = []
    try:
        import pydantic
    except ImportError:
        missing.append("pydantic")
    try:
        import httpx
    except ImportError:
        missing.append("httpx")
    return missing


# Check dependencies at module load time
_missing_deps = check_dependencies()


def pytest_configure(config):
    """Register custom markers."""
    config.addinivalue_line(
        "markers", "requires_deps: mark test as requiring all dependencies"
    )
    config.addinivalue_line(
        "markers", "graphrag_live: mark test as requiring live GraphRAG service"
    )


def pytest_addoption(parser):
    """Add custom command line options."""
    parser.addoption(
        "--graphrag-live",
        action="store_true",
        default=False,
        help="Run tests against live GraphRAG service at http://localhost:18000"
    )


def pytest_collection_modifyitems(config, items):
    """Skip tests that require dependencies if they're missing."""
    if _missing_deps:
        skip_marker = pytest.mark.skip(
            reason=f"Missing dependencies: {', '.join(_missing_deps)}. "
            f"Run tests in Docker: docker compose run --rm backend pytest tests/"
        )
        for item in items:
            item.add_marker(skip_marker)


# Mock enhanced_logger for cleaner test output
class MockLogger:
    def info(self, msg, *args, **kwargs): pass
    def debug(self, msg, *args, **kwargs): pass
    def warning(self, msg, *args, **kwargs): pass
    def error(self, msg, *args, **kwargs): pass
    def critical(self, msg, *args, **kwargs): pass
    def bind(self, **kwargs): return self


# Only set up mocks if dependencies are available
if not _missing_deps:
    # Create the mock module properly
    enhanced_logger_module = ModuleType('enhanced_logger')
    enhanced_logger_module.enhanced_logger = MockLogger()
    sys.modules['enhanced_logger'] = enhanced_logger_module

    # Create a stub modules package that allows submodule imports
    # but doesn't have side effects from __init__.py
    modules_pkg = ModuleType('modules')
    modules_pkg.__path__ = [str(backend_dir / 'modules')]
    modules_pkg.__file__ = str(backend_dir / 'modules' / '__init__.py')
    sys.modules['modules'] = modules_pkg


# GraphRAG Test Fixtures

@pytest.fixture
def graphrag_url():
    """Get GraphRAG service URL."""
    return os.getenv("GRAPHRAG_URL", "http://localhost:18000")


@pytest.fixture
def mock_graphrag_search_response():
    """Mock GraphRAG search response."""
    return {
        "answer": "This is a test answer generated by the LLM.",
        "results": [
            {
                "content": "Test document content about machine learning.",
                "source": "test_doc.pdf",
                "score": 0.92,
                "metadata": {"page": 1}
            },
            {
                "content": "Another relevant document about AI.",
                "source": "ai_doc.txt",
                "score": 0.85,
                "metadata": {}
            }
        ],
        "query_analysis": {
            "intent": "factual",
            "entities": ["Machine Learning", "AI"],
            "keywords": ["learning", "intelligence"],
            "complexity": 3
        },
        "search_method_used": "hybrid",
        "total_results": 2,
        "sources": ["test_doc.pdf", "ai_doc.txt"]
    }


@pytest.fixture
def mock_graphrag_entity_response():
    """Mock GraphRAG entity extraction response."""
    return {
        "entities": [
            {"name": "OpenAI", "type": "organization", "confidence": 0.95, "description": "AI research company"},
            {"name": "GPT-4", "type": "technology", "confidence": 0.92, "description": "Large language model"},
            {"name": "ChatGPT", "type": "product", "confidence": 0.90, "description": "AI chatbot"}
        ],
        "relationships": [
            {"source": "OpenAI", "target": "GPT-4", "relation": "developed", "confidence": 0.88},
            {"source": "OpenAI", "target": "ChatGPT", "relation": "created", "confidence": 0.87},
            {"source": "ChatGPT", "target": "GPT-4", "relation": "powered_by", "confidence": 0.85}
        ],
        "entity_count": 3,
        "relationship_count": 3
    }


@pytest.fixture
def mock_graphrag_reasoning_response():
    """Mock GraphRAG reasoning response."""
    return {
        "reasoning_path": [
            {"hop": 1, "entity": "Machine Learning", "relation": "is_subset_of", "confidence": 0.9},
            {"hop": 2, "entity": "Artificial Intelligence", "relation": "uses", "confidence": 0.85},
            {"hop": 3, "entity": "Neural Networks", "relation": "implements", "confidence": 0.82}
        ],
        "answer": "Machine Learning is a subset of Artificial Intelligence that uses Neural Networks.",
        "sources": [
            {"content": "ML is part of AI...", "source": "ai_textbook.pdf", "score": 0.9}
        ],
        "hop_count": 3
    }


@pytest.fixture
def sample_document_content():
    """Sample document for testing."""
    return """
    Artificial Intelligence and Machine Learning
    
    Machine learning is a subset of artificial intelligence that focuses on
    enabling computers to learn from data without being explicitly programmed.
    
    Deep learning is a specialized form of machine learning that uses neural
    networks with multiple layers. These networks are inspired by the structure
    and function of the human brain.
    
    Key Concepts:
    - Supervised Learning: Training with labeled data
    - Unsupervised Learning: Finding patterns in unlabeled data
    - Reinforcement Learning: Learning through trial and error
    
    Applications include image recognition, natural language processing,
    autonomous vehicles, and medical diagnosis.
    """


@pytest.fixture
async def mock_execution_context():
    """Create mock execution context for workflow executors."""
    from unittest.mock import Mock
    
    context = Mock()
    context.log = Mock()
    context.workflow_id = "test-workflow-id"
    context.execution_id = "test-execution-id"
    context.node_id = "test-node-id"
    context.variables = {}
    context.get_variable = lambda k: context.variables.get(k)
    context.set_variable = lambda k, v: context.variables.update({k: v})
    
    return context
